### ISSUE TITLE
< ColorDescription /> CSS modules migration

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#101]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5372839441)

[CSS modules migration guideline](https://github.com/mondaycom/vibe-storybook-components/blob/master/CSS_MODULES_MIGRATION.md)

**Comment by Dhoni77** [comment]
I would like to take this up

**Comment by SergeyRoyt** [comment]
Closed thanks to @Dhoni77
