### ISSUE TITLE
Create basic story for < FunctionArguments />, < InformationBox />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#103]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5372856405)

Add basic story by structure similar to existing ones

https://github.com/mondaycom/vibe-storybook-components/blob/master/COMPONENTS_DOCUMENTATION_GUIDELINES.md

**Comment by Dhoni77** [comment]
I would like to take this up too.

**Comment by SergeyRoyt** [comment]
Thanks a lot, @Dhoni77 !
It's yours :)

**Comment by Dhoni77** [comment]
Hi @SergeyRoyt In the `<FunctionArgument/>` component I could see that the

**Comment by SergeyRoyt** [comment]
Closed thanks to @Dhoni77 !
