### ISSUE TITLE
docs: Add story for < Title /> component

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#25]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5273128652)

Add simple story by structure similar to the `UsageGuidelines` story, maybe even without `Usage` section
Mention that this component can be used as a replacement for `h3` using storybook `preview` file

**Comment by thezeeshann** [comment]
@SergeyRoyt can you assign me this issue?

**Comment by SergeyRoyt** [comment]
Thanks, @thezeeshann !
Let me just finish the contributing guidelines and I'll assign it to you :)

**Comment by SergeyRoyt** [comment]
@thezeeshann it's yours ;) Please check also these guides:
- https://github.com/mondaycom/vibe-storybook-components/blob/master/CONTRIBUTING.md
- https://github.com/mondaycom/vibe-storybook-components/blob/master/COMPONENTS_DOCUMENTATION_GUIDELINES.md

**Comment by SergeyRoyt** [comment]
Thanks @balajik ! It's yours

**Comment by SergeyRoyt** [comment]
Closed thanks to @balajik !
