### ISSUE TITLE
TS migration: < ComponentRule />, < ComponentRules />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#38]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5294602570)

[Typescript migration guideline](https://github.com/mondaycom/vibe-storybook-components/blob/master/TYPESCRIPT_MIGRATION.md)

**Comment by Kritik-J** [comment]
@SergeyRoyt Please assign this to me

**Comment by SoumyadiptoPal** [comment]
@SergeyRoyt please assign this issue to me

**Comment by SergeyRoyt** [comment]
Hey, @Kritik-J !
You were the first, so it's yours! ;)

@SoumyadiptoPal we'll have the other tasks soon 🙏

**Comment by SergeyRoyt** [comment]
Closed thanks to @Kritik-J !
