### ISSUE TITLE
TS migration: < FunctionArgument />, < FunctionArguments />, < MultipleStoryElementsWrapper />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#40]
https://monday.monday.com/boards/3532714909/pulses/5294605423

[Typescript migration guideline](https://github.com/mondaycom/vibe-storybook-components/blob/master/TYPESCRIPT_MIGRATION.md)

**Comment by SoumyadiptoPal** [comment]
@SergeyRoyt can you please assign this issue to me?

**Comment by SergeyRoyt** [comment]
Hey @balajik!
You were the first, so it's yours ;)

**Comment by SergeyRoyt** [comment]
@balajik this one you mean? What's wrong here?
<img width="108" alt="image" src="https://github.com/mondaycom/vibe-storybook-components/assets/104433616/cc6e5eae-74db-4c1b-9539-97366847eab9">

**Comment by SergeyRoyt** [comment]
Oh, you are right! Thanks a lot! ^_^

**Comment by SergeyRoyt** [comment]
Solved, thanks to @balajik !
