### ISSUE TITLE
CSS modules migration: < UsageGuidelines />, < VisualDescription />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#42]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5294616972)

[CSS modules migration guideline](https://github.com/mondaycom/vibe-storybook-components/blob/master/CSS_MODULES_MIGRATION.md)

**Comment by Kritik-J** [comment]
@SergeyRoyt i would like to work on it, Please assign this to me

**Comment by SergeyRoyt** [comment]
It's yours @Kritik-J! :)

**Comment by SergeyRoyt** [comment]
Thanks for the contribution! 😃
