### ISSUE TITLE
CSS modules migration: < SectionName />, < RelatedComponent />, < RelatedComponents />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#43]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5294617235)

[CSS modules migration guideline](https://github.com/mondaycom/vibe-storybook-components/blob/master/CSS_MODULES_MIGRATION.md)

**Comment by Kritik-J** [comment]
@SergeyRoyt Please assign this to me

**Comment by SergeyRoyt** [comment]
Assigned to you! 😉

**Comment by SergeyRoyt** [comment]
Resolved, thanks to @Kritik-J !
