### ISSUE TITLE
docs: theme switcher in the storybook

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#50]
We want to implement here the same functionality we have in `monday-ui-react-core` storybook - theme switching
https://github.com/mondaycom/monday-ui-react-core
https://style.monday.com/?path=/story/welcome--page

<img width="502" alt="image" src="https://github.com/mondaycom/vibe-storybook-components/assets/104433616/48147bcf-e9cc-4c1b-b944-ca8390bb7be3">

There we are using storybook 6 and we are using [storybook-addon-themes](https://storybook.js.org/addons/storybook-addon-themes) for this - it just adds a classname somewhere to the body level and our components tokens know how to adapt to it + it also sets the background color for the whole page.
<img width="695" alt="image" src="https://github.com/mondaycom/vibe-storybook-components/assets/104433616/71e95ba9-b4a1-4ef2-aef7-bb202870633e">

Here we are using storybook 7 and this addon is not supporting it, so we need to find some other solution for it

UPD: new theme-switcher addon was released https://storybook.js.org/blog/introducing-theme-switcher-addon

**Comment by pedaars** [comment]
I would like to take this please

**Comment by SergeyRoyt** [comment]
Thanks, @pedaars! It's yours
Good luck with that! 
Feel free to ask any questions if needed :)

**Comment by pedaars** [comment]
@SergeyRoyt Well that was interesting I think I have it working using a new addon released for v7 of storybook but I need a component story that is available in both this storybook and https://style.monday.com/?path=/story/welcome--page so I can compare.

Is anyone working on any?

**Comment by SergeyRoyt** [comment]
> @SergeyRoyt Well that was interesting I think I have it working using a new addon released for v7 of storybook but I need a component story that is available in both this storybook and https://style.monday.com/?path=/story/welcome--page so I can compare.
> 
> Is anyone working on any?

Hey @pedaars !
Let's try to compare e.g. `Tip` component from vibe-storybook-components and `AttentionBox` from `monday-ui-react-core` - https://style.monday.com/?path=/story/feedback-attentionbox--states. It's not 100% exactly the same component, but in terms of colors should behave the same
Here is how it should look e.g. in a Dark theme
![image](https://github.com/mondaycom/vibe-storybook-components/assets/104433616/936d12a4-d668-4fdc-ac39-94aa561c303d)


For test I've applied `dark-app-theme` in `vibe-storybook-components` storybook to the outer div, here is what I've achieved 
![image](https://github.com/mondaycom/vibe-storybook-components/assets/104433616/bf0ce129-3b53-4705-af89-778836322f8f)
Colors doesn't look too good, but good news they've changed - so you should get smth similar if the theme-switcher is working fine

**Comment by pedaars** [comment]
Thanks for that. Ok so my solution is working and I have raised a pr

**Comment by SergeyRoyt** [comment]
Closed thanks to @pedaars!
