### ISSUE TITLE
docs: Add story for < ComponentName /> component 

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#56]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5318797037)

Add simple story by structure similar to the `UsageGuidelines` story, maybe even without `Usage` section
Mention that this component can be used as a replacement for `h1` using storybook `preview` file

- https://github.com/mondaycom/vibe-storybook-components/blob/master/CONTRIBUTING.md
- https://github.com/mondaycom/vibe-storybook-components/blob/master/COMPONENTS_DOCUMENTATION_GUIDELINES.md

**Comment by Dhoni77** [comment]
Hi @SergeyRoyt  I would like to take this up

**Comment by SergeyRoyt** [comment]
Thanks, @Dhoni77 ! It's yours :)

**Comment by SergeyRoyt** [comment]
Closed thanks to @Dhoni77
