### ISSUE TITLE
TS migration: < UsageGuidelines />, < VisualDescription />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#63]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5331923418)

[Typescript migration guideline](https://github.com/mondaycom/vibe-storybook-components/blob/master/TYPESCRIPT_MIGRATION.md)

**Comment by Kritik-J** [comment]
SergeyRoyt Please assign this to me

**Comment by SergeyRoyt** [comment]
Closed thanks to @Kritik-J !
