### ISSUE TITLE
TS migration: < SectionName />, < RelatedComponent />, < RelatedComponents />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#64]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5331927464)

[Typescript migration guideline](https://github.com/mondaycom/vibe-storybook-components/blob/master/TYPESCRIPT_MIGRATION.md)

**Comment by Kritik-J** [comment]
@SergeyRoyt  Please assign this to me

**Comment by r0ld3x** [comment]
@SergeyRoyt  assign me

**Comment by SergeyRoyt** [comment]
Hey! 
Assigned to @Kritik-J as he was the first

@r0ld3x we'll soon create other issue 🙂

**Comment by SergeyRoyt** [comment]
Closed thanks to @Kritik-J ! 🥳
