### ISSUE TITLE
CSS modules migration: < ComponentRule />, < ComponentRules />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#68]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5333672767)

[CSS modules migration guideline](https://github.com/mondaycom/vibe-storybook-components/blob/master/CSS_MODULES_MIGRATION.md)

**Comment by Dhoni77** [comment]
Hi @SergeyRoyt  I would like to take this up

**Comment by SergeyRoyt** [comment]
Thanks, @Dhoni77 !
You are on it! 🙂

**Comment by SergeyRoyt** [comment]
Closed thanks to @Dhoni77 !
