### ISSUE TITLE
TS migration: < Link />, < StoryDescription />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#76]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5336788875)

[Typescript migration guideline](https://github.com/mondaycom/vibe-storybook-components/blob/master/TYPESCRIPT_MIGRATION.md)

**Comment by SergeyRoyt** [comment]
Thanks, @Dhoni77!
Assigned to you 😉

**Comment by aryab2003** [comment]
Hi,@SergeyRoyt ,Ihave made the required changes in the <Link/>.Please help me if other changes are required.

**Comment by SergeyRoyt** [comment]
Closed thanks to @Dhoni77 !
