### ISSUE TITLE
docs: Create basic story for < ComponentDescription />, < UnstyledList /> + < UnstyledListItem />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#89]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5350282741)

Add basic story by structure similar to existing ones
Use `UnstyledListItem` in `UnstyledList` story

- https://github.com/mondaycom/vibe-storybook-components/blob/master/CONTRIBUTING.md
- https://github.com/mondaycom/vibe-storybook-components/blob/master/COMPONENTS_DOCUMENTATION_GUIDELINES.md

**Comment by Dhoni77** [comment]
Hi @SergeyRoyt I would like to work on this

**Comment by SergeyRoyt** [comment]
Hey, @Dhoni77 ! You got it ;)

**Comment by SergeyRoyt** [comment]
Solved by @Dhoni77 !
