### ISSUE TITLE
docs: Create basic story for < VisualDescription />, < ColorDescription />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe-storybook-components#92]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5350388750)

Add basic story by structure similar to existing ones

- https://github.com/mondaycom/vibe-storybook-components/blob/master/CONTRIBUTING.md
- https://github.com/mondaycom/vibe-storybook-components/blob/master/COMPONENTS_DOCUMENTATION_GUIDELINES.md

**Comment by Dhoni77** [comment]
I would like to work on this

**Comment by SergeyRoyt** [comment]
Closed thanks to @Dhoni77! 💪
